services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      mysql_HOST: mysql
      mysql_USER: ${MYSQL_USER}
      mysql_PASSWORD: ${MYSQL_PASSWORD}
      mysql_NAME: ${MYSQL_DATABASE}
    command: [ "sh", "-c", "apt-get update && apt-get install -y netcat-traditional && until nc -z mysql 3306; do sleep 1; done && node server.js" ]

  mysql:
    image: mysql:9.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
